name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
    inputs:
      os:
        description: "Runs on OS"
        required: true
        default: windows-latest
        type: choice
        options:
          - windows-latest
          - ubuntu-latest
          - alpine-latest

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ github.event.inputs.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose --release
      - name: Run tests
        run: cargo test --verbose
      - name: Package the binary
        run: mkdir output/ && cp -f target/release/uof-status output/
      - name: Release the binary
        uses: actions/upload-artifact@v3
        with:
          name: uof-status
          path: output/