name: Linux x86_64 musl
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  CARGO_TERM_COLOR: always
  BUILD_TARGET: x86_64-unknown-linux-musl
  BINARY_NAME: uof-status_x86_64-linux-musl
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build-musl
      uses: gmiam/rust-musl-action@master
      with:
        args: cargo build --target=$BUILD_TARGET --release
    - uses: actions/upload-artifact@v3
      with:
        name: ${{ env.BINARY_NAME }}
        path: target/${{ env.BINARY_TARGET }}/release/uof-status*
